on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: autoconf && automake && ./autogen.sh && ./configure && make -e LDFLAGS='-L/usr/local/lib -z muldefs'
