on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: apt-get update -yq && apt-get install -yq automake autotools && ./configure && make
