on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: /bin/sh autogen.sh && ./configure && make -e LDFLAGS='-L/usr/local/lib -z muldefs'
