on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo $PATH
          echo $CWD
          echo $PWD
          sudo apt-get install -yq fltk1.3-dev bash libtool autoconf automake
          cd /home/runner/work/dillo/dillo 
          autoupdate
          libtoolize
          ./autogen.sh 
          ./configure 
          make -e LDFLAGS='-L/usr/local/lib -z muldefs'
